# Generated by Django 2.2.2 on 2021-11-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='learning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='タイトル')),
                ('content', models.TextField(blank=True, null=True, verbose_name='本文  ')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真1 ')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真2 ')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真3 ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name_plural': 'learning',
            },
        ),
    ]
