# Generated by Django 2.2.2 on 2021-11-29 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learning',
            name='content',
        ),
        migrations.RemoveField(
            model_name='learning',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='learning',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='learning',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='learning',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='learning',
            name='title',
        ),
        migrations.RemoveField(
            model_name='learning',
            name='updated_at',
        ),
    ]
